server {
    listen 80;
    listen [::]:80;
    server_name hunt.lost-deviation.com;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/hunt-acme;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
